# Generated by Django 2.1.7 on 2019-06-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creater_id', models.IntegerField(default=0, verbose_name='创建者')),
                ('album_id', models.IntegerField(default=0, verbose_name='相册id')),
                ('picture_id', models.IntegerField(default=0, verbose_name='图片id')),
                ('parent_reply', models.IntegerField(verbose_name='回复的回复id')),
                ('content', models.CharField(default='', max_length=128, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '图片回复',
                'verbose_name_plural': '图片回复',
            },
        ),
        migrations.RemoveField(
            model_name='album',
            name='user_id',
        ),
        migrations.AddField(
            model_name='album',
            name='creater_id',
            field=models.IntegerField(default=0, verbose_name='创建者id'),
        ),
        migrations.AlterField(
            model_name='album',
            name='desc',
            field=models.CharField(default='', max_length=64, verbose_name='相册描述'),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(default='', max_length=16, verbose_name='相册标题'),
        ),
        migrations.AlterField(
            model_name='albumcategory',
            name='name',
            field=models.CharField(default='', max_length=16, verbose_name='分类名'),
        ),
        migrations.AlterField(
            model_name='albumtag',
            name='name',
            field=models.CharField(default='', max_length=16, verbose_name='标签名'),
        ),
    ]
