# Generated by Django 2.1.7 on 2019-06-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0003_auto_20190610_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='category',
            field=models.IntegerField(default=0, verbose_name='种类'),
        ),
    ]
