# Generated by Django 2.2.1 on 2019-06-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0004_album_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='first_picture_id',
            field=models.IntegerField(default=0, verbose_name='第一张图片 id'),
        ),
    ]
