# Generated by Django 2.1.7 on 2019-06-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0006_auto_20190610_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='tags',
            field=models.ManyToManyField(blank=True, to='picture.AlbumTag', verbose_name='标签'),
        ),
    ]
