# Generated by Django 2.1.7 on 2019-06-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0007_auto_20190610_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.IntegerField(default=0, verbose_name='相册id')),
                ('creater_id', models.IntegerField(default=0, verbose_name='点赞人id')),
                ('creater_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '点赞',
                'verbose_name_plural': '点赞',
            },
        ),
        migrations.AlterModelOptions(
            name='favoritealbum',
            options={'verbose_name': '收藏', 'verbose_name_plural': '收藏'},
        ),
        migrations.AlterField(
            model_name='favoritealbum',
            name='creater_id',
            field=models.IntegerField(default=0, verbose_name='收藏人id'),
        ),
    ]
