# Generated by Django 2.1.7 on 2019-06-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0008_auto_20190615_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='album_id',
            field=models.IntegerField(default=0, verbose_name='相册 id'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='desc',
            field=models.CharField(default='', max_length=64, verbose_name='描述'),
        ),
    ]
