# Generated by Django 2.1.7 on 2019-06-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationInUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.IntegerField(verbose_name='关注者')),
                ('to_user', models.IntegerField(verbose_name='被关注者')),
                ('relation', models.CharField(choices=[('1', '关注'), ('2', '朋友')], max_length=1, verbose_name='双方关系')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
