# Generated by Django 2.1.7 on 2019-06-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190607_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationinuser',
            options={'verbose_name': '用户关系', 'verbose_name_plural': '用户关系'},
        ),
    ]
