# Generated by Django 2.1.7 on 2019-06-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190607_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationinuser',
            name='relation',
            field=models.PositiveSmallIntegerField(choices=[(1, '关注'), (2, '朋友')], verbose_name='双方关系'),
        ),
    ]
